# Existing Materials Data

EXISTING_MATERIALS = [
    {'CategoryName': 'paper', 'Description': 'Corrugated Containers', 'CO2Savings': 5.58},
    {'CategoryName': 'paper', 'Description': 'Magazines/third-class mail', 'CO2Savings': 8.57},
    {'CategoryName': 'paper', 'Description': 'Newspaper', 'CO2Savings': 4.68},
    {'CategoryName': 'paper', 'Description': 'Office Paper', 'CO2Savings': 7.95},
    {'CategoryName': 'paper', 'Description': 'Phonebooks', 'CO2Savings': 6.17},
    {'CategoryName': 'paper', 'Description': 'Textbooks', 'CO2Savings': 9.02},
    {'CategoryName': 'paper', 'Description': 'Mixed Paper (general)', 'CO2Savings': 6.07},
    {'CategoryName': 'paper', 'Description': 'Mixed Paper (primarily)', 'CO2Savings': 6.00},
    {'CategoryName': 'paper', 'Description': 'Mixed Paper (primarily from Food Waste)', 'CO2Savings': 3.66},
    {'CategoryName': 'organic', 'Description': 'Food Waste (non-meat)', 'CO2Savings': 0.76},
    {'CategoryName': 'organic', 'Description': 'Food Waste (meat only)', 'CO2Savings': 15.1},
    {'CategoryName': 'organic', 'Description': 'Beef', 'CO2Savings': 30.9},
    {'CategoryName': 'organic', 'Description': 'Poultry', 'CO2Savings': 2.45},
    {'CategoryName': 'organic', 'Description': 'Grains', 'CO2Savings': 0.62},
    {'CategoryName': 'organic', 'Description': 'Bread', 'CO2Savings': 0.66},
    {'CategoryName': 'organic', 'Description': 'Fruits and Vegetables', 'CO2Savings': 0.44},
    {'CategoryName': 'organic', 'Description': 'Dairy Products', 'CO2Savings': 1.75},
    {'CategoryName': 'plastic', 'Description': 'HDPE', 'CO2Savings': 1.42},
    {'CategoryName': 'plastic', 'Description': 'LDPE', 'CO2Savings': 1.80},
    {'CategoryName': 'plastic', 'Description': 'PET', 'CO2Savings': 2.17},
    {'CategoryName': 'plastic', 'Description': 'LLDPE', 'CO2Savings': 1.58},
    {'CategoryName': 'plastic', 'Description': 'PP', 'CO2Savings': 1.00},
    {'CategoryName': 'plastic', 'Description': 'PS', 'CO2Savings': 2.50},
    {'CategoryName': 'plastic', 'Description': 'PVC', 'CO2Savings': 1.93},
    {'CategoryName': 'plastic', 'Description': 'Mixed Plastics', 'CO2Savings': 1.87},
    {'CategoryName': 'plastic', 'Description': 'PLA', 'CO2Savings': 2.45},
    {'CategoryName': 'electronics', 'Description': 'Desktop CPUs', 'CO2Savings': 20.80},
    {'CategoryName': 'electronics', 'Description': 'Portable Electronic Devices', 'CO2Savings': 29.83},
    {'CategoryName': 'electronics', 'Description': 'Flat-Panel Displays', 'CO2Savings': 24.19},
    {'CategoryName': 'electronics', 'Description': 'Electronic Peripherals', 'CO2Savings': 10.32},
    {'CategoryName': 'electronics', 'Description': 'Hard-Copy Devices', 'CO2Savings': 7.65},
    {'CategoryName': 'electronics', 'Description': 'Mixed Electronics', 'CO2Savings': 20.79},
    {'CategoryName': 'metal', 'Description': 'Aluminum Cans', 'CO2Savings': 4.80},
    {'CategoryName': 'metal', 'Description': 'Aluminum Ingot', 'CO2Savings': 7.48},
    {'CategoryName': 'metal', 'Description': 'Steel Cans', 'CO2Savings': 3.03},
    {'CategoryName': 'metal', 'Description': 'Copper Wire', 'CO2Savings': 6.72},
    {'CategoryName': 'metal', 'Description': 'Mixed Metals', 'CO2Savings': 3.65},
    {'CategoryName': 'glass', 'Description': 'Glass', 'CO2Savings': 0.53},
    {'CategoryName': 'construction', 'Description': 'Asphalt Concrete', 'CO2Savings': 0.19},
    {'CategoryName': 'construction', 'Description': 'Asphalt Shingles', 'CO2Savings': 0.19},
    {'CategoryName': 'construction', 'Description': 'Carpet', 'CO2Savings': 3.68},
    {'CategoryName': 'construction', 'Description': 'Clay Bricks', 'CO2Savings': 0.27},
    {'CategoryName': 'construction', 'Description': 'Dimensional Lumber', 'CO2Savings': 2.11},
    {'CategoryName': 'construction', 'Description': 'Drywall', 'CO2Savings': 0.00},
    {'CategoryName': 'construction', 'Description': 'Fiberglass Insulation', 'CO2Savings': 0.38},
    {'CategoryName': 'construction', 'Description': 'Medium-density Fiberboard', 'CO2Savings': 3.05},
    {'CategoryName': 'construction', 'Description': 'Structural Steel', 'CO2Savings': 1.67},
    {'CategoryName': 'construction', 'Description': 'Vinyl Flooring', 'CO2Savings': 0.58},
    {'CategoryName': 'construction', 'Description': 'Wood Flooring', 'CO2Savings': 4.11},
    {'CategoryName': 'tires', 'Description': 'Tires', 'CO2Savings': 4.30}
]